### ISSUE TITLE
Channel Todo

### ISSUE THREAD

**Issue by atymic** [laravel-notification-channels/pushwoosh#1]
- [x] Code Review
- [x] Add @axlon as repo admin
- [x] Add to website
- [x] Create packagist package
- [x] Add badges

**Comment by axlon** [comment]
Its up, please see #2

**Comment by axlon** [comment]
@atymic I am unable to add this package to packagist because I'm not a member of the organization (I think?).

**Comment by atymic** [comment]
Yep, we need @themsaid to do it (i don't have access either).

**Comment by atymic** [comment]
@axlon 

It's live now. You can tag the first release when you are ready.
https://packagist.org/packages/laravel-notification-channels/pushwoosh

**Comment by atymic** [comment]
Could you also create a PR to add the badges :)

**Comment by axlon** [comment]
I'll be doing some real world testing in the following 1-2 weeks, if successful I'll tag it after.

Im in the process of adding integrations to the repo but I'm running in the issue where (much like with Packagist) StyleCI doesn't "see" the repository because I'm not part of the organization. Is there a way around this or can you maybe add me to the organization so I can access the repository in StyleCI?

**Comment by atymic** [comment]
Sweet, sounds good. 

I've added StyleCI
